services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neynar_parquet_importer
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    # restart: unless-stopped
    volumes:
      - ./data/parquet:/app/data/parquet
      # # sharing `.aws` is only required if you have your AWS credentials on the host machine instead of in `.env`
      - $HOME/.aws:/root/.aws
